### ISSUE TITLE
Excluding Tables From The Dump

### ISSUE THREAD

**Issue by Blair2004** [spatie/laravel-db-snapshots#105]
Hi, so I'm using this package for a while and I use it for backup purposes (that works for me). However, as I'm using laravel/telescope, I'm often forced to prune the database before doing a backup (which makes me lose my records). I was wondering if there is any way to exclude specific tables from the backup?

**Comment by hjanos-bc** [comment]
This package uses [db-dumper](https://github.com/spatie/db-dumper) internally. You can configure db-dumper via the dump key in your database configuration.

[Relevant source code](https://github.com/spatie/laravel-db-snapshots/blob/445c6a86b34fef08d229b541e887bc521ad9f036/src/DbDumperFactory.php#L46)

Example:
`
'connections' => [

        // ...

        'mysql' => [
            // ...
            'dump' =>[
                'excludeTables' => [
                    'table_to_exclude_1',
                    'table_to_exclude_2',
                    // ...
                ],
            ],
            // ...
        ],

        // ...
];
`

**Comment by Blair2004** [comment]
Thank you... i'm late to close the thread sorry @freekmurze
