### ISSUE TITLE
I am not able to install the package.

### ISSUE THREAD

**Issue by sandeshpoudel** [spatie/laravel-db-snapshots#107]
$ composer require spatie/laravel-db-snapshots
Using version ^1.6 for spatie/laravel-db-snapshots
./composer.json has been updated
Running composer update spatie/laravel-db-snapshots
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - spatie/laravel-db-snapshots 1.6.0 requires illuminate/support ^6.0|^7.0 -> found illuminate/support[v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev] but it conflicts with another require.
    - spatie/laravel-db-snapshots[1.6.1, ..., 1.7.0] require php ^7.4 -> your php version (7.3.11) does not satisfy that requirement.
    - Root composer.json requires spatie/laravel-db-snapshots ^1.6 -> satisfiable by spatie/laravel-db-snapshots[1.6.0, 1.6.1, 1.6.2, 1.7.0].

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

**Comment by freekmurze** [comment]
Please use PHP 7.4
