### ISSUE TITLE
Undefined array key "extension" when running ListSnapshots command

### ISSUE THREAD

**Issue by eli-s-r** [spatie/laravel-db-snapshots#117]
When I run `php artisan snapshot:list`, I get the error `Undefined array key "extension"` on [this line](https://github.com/spatie/laravel-db-snapshots/blob/ca25ad097fd19d855e4cc1662186dde5b55c1177/src/SnapshotRepository.php#L22). For what it's worth I am using `s3` as my driver instead of `local` in case that makes any difference :)

Is it possible that the folders in the bucket (which don't have extensions) are being parsed as files, and so don't have an extension listed?

**Comment by eli-s-r** [comment]
Update: it looks like what I suspected above is correct, as when I changed the `root` config on the disk in my `filesystems.php` to `snapshots`, all snapshots were uploaded in the `snapshots` folder and listed correctly. Though loading is not working due to a different error (that I will make a separate issue for)

**Comment by freekmurze** [comment]
Feel free to submit a PR that fixes this.

**Comment by eli-s-r** [comment]
Closing due to #120 being merged in
