### ISSUE TITLE
 The "--table" option does not exist.

### ISSUE THREAD

**Issue by kevinaichat** [spatie/laravel-db-snapshots#123]
Im trying to do a snapshot of specific tables in my DB but the `--table=table1,table2` seems like not working. 
![image](https://user-images.githubusercontent.com/108515579/176848569-3834e060-8ca5-4f93-89b8-4db5dfb122b8.png)

**Comment by jimtaylor123** [comment]
Perhaps you are running a very early version of laravel snapshots - it wasn't available in earlier versions.
