### ISSUE TITLE
Difference between your other package "Laravel Backup"?

### ISSUE THREAD

**Issue by FR6** [spatie/laravel-db-snapshots#15]
Can you tell me what's the difference between this package and your other one "[Laravel Backup](https://github.com/spatie/laravel-backup)"?

**Comment by freekmurze** [comment]
One is made for automated backups, the other for manually quickly dumping and loading the db.

Go over the docs of both packages to find out all the differences.

**Comment by FR6** [comment]
I understand that in terms of functionality both are different but I'm trying to understand why you guys have not merged the functionality in the same package?

I didn't try snapshots but thank you for your backup package, it is really useful!

**Comment by sebastiandedeyne** [comment]
One use case for this package is when you're developing a feature (locally), and need to have the database in a specific state to follow the feature's flow, you'd save a snapshot of the database, try out your feature, see bugs, attempt to fix bugs, reset database, and repeat.
