### ISSUE TITLE
Issues with mysqldump on Mac

### ISSUE THREAD

**Issue by nexxai** [spatie/laravel-db-snapshots#18]
```
➜  application git:(master) ✗ php artisan snapshot:create seed-with-data
Creating new snapshot...

                                                                                                    
  [Spatie\DbDumper\Exceptions\DumpFailed]                                                           
  The dump process failed with exitcode 127 : Command not found : sh: mysqldump: command not found  
                                                                                                    

➜  application git:(master) ✗ which mysqldump
mysqldump not found
➜  application git:(master) ✗ export PATH=/Applications/MySQLWorkbench.app/Contents/MacOS:$PATH
➜  application git:(master) ✗ php artisan snapshot:create seed-with-data                       
Creating new snapshot...

                                                                                                           
  [Spatie\DbDumper\Exceptions\DumpFailed]                                                                  
  The dump process failed with exitcode 2 : Misuse of shell builtins : mysqldump: Got error: 2003: Can't   
  connect to MySQL server on '127.0.0.1' (61) when trying to connect                                       
                                                                                                           
```

At this point I don't know enough about the mysql tools to know what that error really means, but I am positive the server is listening on 127.0.0.1 as per my .env file:

```
DB_HOST=127.0.0.1
DB_PORT=3306
DB_DATABASE=application
DB_USERNAME=app
DB_PASSWORD=app
```

Anyone have any ideas?

**Comment by freekmurze** [comment]
This package uses `mysqldump` to dump the contents of a database to a file. It seems like the binary is not found on your system. Google a bit around to learn how to install it on your server.

**Comment by freekmurze** [comment]
Pretty sure this is caused by something specific to your machine. Have you tried moving the binary to a standard location eg `/usr/local/bin`?

**Comment by bayareawebpro** [comment]
@nexxai I found the answer in a previous issue on this repo,  as I was having the problem myself.  You can this array to config/database.php to specify the path to the dump command.

 'dump' => [ 'dump_binary_path' => '/Applications/MAMP/Library/bin/' ]

**Comment by seandelaney** [comment]
@bayareawebpro

Where did you add `'dump' => [ 'dump_binary_path' => '/Applications/MAMP/Library/bin/' ]` in `config/database.php` ?

**Comment by bayareawebpro** [comment]
/usr/local/bin/mysqldump is the default on OSX.  

If you use MAMP or another server environment that has it's own MYSQL you have to specify the correct path to the binary otherwise the MYSQL you are trying to dump will have no data in it.

Correct that goes in config/database.php


`'mysql' => [
            'driver' => 'mysql',
            'host' => env('DB_HOST', '127.0.0.1'),
            'port' => env('DB_PORT', '3306'),
            'database' => env('DB_DATABASE', 'forge'),
            'username' => env('DB_USERNAME', 'forge'),
            'password' => env('DB_PASSWORD', ''),
            'unix_socket' => env('DB_SOCKET', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => true,
            'engine' => null,
            'dump' => [ 'dump_binary_path' => '/Applications/MAMP/Library/bin/' ]
        ],`

**Comment by seandelaney** [comment]
@bayareawebpro 

Just want to check that you are replacing `dump_binary_path` with `/usr/local/bin/` or whatever path your mysqldump exists at, right ?

**Comment by bayareawebpro** [comment]
@seandelaney no, that is an array key that's needed.  Should look like this:

'dump_binary_path' => 'YOUR_PATH_HERE'
-OR- 
'dump_binary_path' => '/usr/local/bin/'
