### ISSUE TITLE
support for mongodb please?

### ISSUE THREAD

**Issue by vesper8** [spatie/laravel-db-snapshots#20]
Hey hey! Guess who! Hehe ;)

So I have this project that uses both mysql and mongodb and I've been using your db-dumper as well as your backup libraries on it which now support both (awesome) and now I want to use this snapshot one too!

So first thing first, I noticed that in your snapshot:create command you accept a "connection" parameter but right now you have it set as a boolean all-or-nothing (doesn't accept a value) which I think is just a typo

On https://github.com/spatie/laravel-db-snapshots/blob/master/src/Commands/Create.php#L13

```
protected $signature = 'snapshot:create {name?} {--connection}';
```

needs to be 

```
protected $signature = 'snapshot:create {name?} {--connection=}';
```

And then you can do this 

```
php artisan snapshot:create --connection mysql
php artisan snapshot:create --connection mongodb
```

:)

But then I tried to dump the mongodb connection and got

```
  Cannot create a dumper for db driver `mongodb`. Use `mysql`, `pgsql` or `sqlite`.
```

But I know you support mongodb already! Just need to add it in

I tried adding 

```
        if ($driver === 'mongodb') {
            return new MongoDb();
        }
```

here https://github.com/spatie/laravel-db-snapshots/blob/master/src/DbDumperFactory.php#L55

But I guess it needs a bit more than that since now I'm getting

```
[Spatie\DbDumper\Exceptions\DumpFailed]
  The dump process failed with exitcode 3 : Unknown error : 2017-05-20T21:58:08.574+0800	positional arguments not allowed: [21:58:08.sql]
  2017-05-20T21:58:08.575+0800	try 'mongodump --help' for more information
```

Now.. I know I could spend the next 30-60 minutes writing a PR and figuring out why it works beautifully in db-dumper but doesn't here.. but I also know that you probably already know exactly what's that other little extra bit that db-snapshots is missing and you can fix it and tag a new release faster than I can make a fork!

THANK YOU!! love all your work! You'll seriously be getting a postcard from me very soon :)

**Comment by freekmurze** [comment]
Unfortunately I don't know a quick fix for this by heart. And because I'm not a user of mongodb, this is pretty low on my priority list.

So could you spend the some times whipping up a PR for this. 

Your fellow mongodb users and I would greatly appreciate that.

**Comment by freekmurze** [comment]
Closing this for now, like mentioned above, feel free to submit a PR.
