### ISSUE TITLE
Any version that supports 5.1 LTS?

### ISSUE THREAD

**Issue by unitedworx** [spatie/laravel-db-snapshots#21]
Is there version of this package that supports laravel 5.1 LTS?

Thanks for the wonderful work

**Comment by freekmurze** [comment]
Nope, if you need L5.1 support, fork the package and maintain your own copy.

**Comment by unitedworx** [comment]
Thanks for the reply, was hoping an older version supported 5.1 at some point. No worries will get some simple artisan commands going to interface with mysqldump to do what I need.
