### ISSUE TITLE
would it be possible to have a flag for dumping content only (no structure, no table dropping)

### ISSUE THREAD

**Issue by vesper8** [spatie/laravel-db-snapshots#22]
I have a specific scenario where I need to dump and load the content only but with modifications to the structure in-between unchanged

currently creating a mysql snapshot has

drop table if exists
create table
lock table
insert content
unlock table

I would like an option to do the following instead:

truncate table
lock table
insert content
unlock table

is this something that is already support by the db-dumper perhaps?

if not, what file would I need to modify and would you be open to a PR to add a flag --content-only --truncate-first kind of thing?

thanks

**Comment by sebastiandedeyne** [comment]
I wouldn't mind this feature in the package

**Comment by vesper8** [comment]
Well for now I created this little bash script that does what I want

```
#!/bin/bash

auth="-uhomestead -psecret"
options="--skip-triggers --no-create-info --add-locks"
sed="| sed -r 's/LOCK TABLES (\`[^\`]+\`)/TRUNCATE TABLE \1; \n\nLOCK TABLES \1/g'"
mysqlCmd="mysqldump ${auth} ${options} ns_bali ${sed} > ns_bali-data-only.sql"
eval "${mysqlCmd}"
```

Not sure how to make it work with this package

**Comment by freekmurze** [comment]
I'm open for a PR to [spatie/db-dumper](https://github.com/spatie/db-dumper) that adds separate methods to add `--content-only` and `--truncate-first` flags.

If those methods are in place, you can use them in this package by just adding snake cased version of those methods names to the `dump` key in the db connection config. 

https://github.com/spatie/laravel-db-snapshots/blob/274e530/src/DbDumperFactory.php#L34

**Comment by freekmurze** [comment]
Going to close this for now. If you have any more questions, feel free to reopen.
