### ISSUE TITLE
Load the snapshot to another DB connection?

### ISSUE THREAD

**Issue by mansouralex** [spatie/laravel-db-snapshots#23]
Hi @freekmurze 

Can we load the database to another DB connection instead of loading the snapshot to the current main connection?

Thanks.

**Comment by mansouralex** [comment]
@freekmurze Setting `default_connection` on run time before running the load command will solve it ?

**Comment by freekmurze** [comment]
Try it out and let me know 😄 

I'd accept a PR that adds a `connection` option to the `load` command.

**Comment by mansouralex** [comment]
@freekmurze  Sounds good. @Te7a-Houdini Lets consider to work on this feature tomorrow.

**Comment by freekmurze** [comment]
Thank you! Make sure you add some tests to prove the new functionality works.

**Comment by mansouralex** [comment]
@freekmurze Do you think it make sense to disable confirmToProceed check when we are loading to non-default connection?
