### ISSUE TITLE
The "--force" option does not exist.

### ISSUE THREAD

**Issue by vesper8** [spatie/laravel-db-snapshots#28]
Running into this problem when trying to use this package with the .env set to Production

I think I might be a framework bug

I want to add I find it extremely useful to use snapshots in production.. especially when multiple sites share the same S3 storage.. for my use case it's made certain tasks a ton easier and easily schedulable

```
[2017-09-25 15:21:28] production.ERROR: The "force" option does not exist. {"exception":"[object] (Symfony\\Component\\Console\\Exception\\InvalidArgumentException(code: 0): The \"force\" option does not exist. at /home/forge/xxx.xxx/current/vendor/symfony/console/Input/Input.php:158)
[stacktrace]
#0 /home/forge/xxx.xxx/current/vendor/laravel/framework/src/Illuminate/Console/Command.php(274): Symfony\\Component\\Console\\Input\\Input->getOption('force')
#1 /home/forge/xxx.xxx/current/vendor/laravel/framework/src/Illuminate/Console/ConfirmableTrait.php(25): Illuminate\\Console\\Command->option('force')
#2 /home/forge/xxx.xxx/current/vendor/spatie/laravel-db-snapshots/src/Commands/Load.php(29): Spatie\\DbSnapshots\\Commands\\Load->confirmToProceed()
#3 [internal function]: Spatie\\DbSnapshots\\Commands\\Load->handle()
```

**Comment by introwit** [comment]
@vesper8 Hey thank you for creating the issue, can you help with listing the steps to reproduce this error?

**Comment by vesper8** [comment]
Sure @introwit 

1- Configure this package to work with S3
2- Create a mysql snapshot
2- Change .env value from local to production
3- try to load the snapshot you just created
4- doesn't work, but if you change production -> local, it works

**Comment by introwit** [comment]
@vesper8 this seems to originate from [here](https://github.com/laravel/framework/blob/bd352a0d2ca93775fce8ef02365b03fc4fb8cbb0/src/Illuminate/Console/ConfirmableTrait.php) in my initial research

**Comment by vesper8** [comment]
So what is the problem? Is the problem that Spatie's package should not be using Confirmable Trait?

Or is the problem on the side of the Laravel Framework?

I opened an issue here https://github.com/laravel/framework/issues/21373 but they just threw the ball back over here

**Comment by bayareawebpro** [comment]
Try with the env flag:  artisan snapshot:load myversion --env=staging

**Comment by mrksohag** [comment]
Check your .env file and database? I got the same issue.  I solve my issue by adding .env file and database after cloning the project.

**Comment by mansouralex** [comment]
@introwit Any updates on this? Just tried @bayareawebpro suggestion and it's not working when the environment is production.
