### ISSUE TITLE
loading from S3 is very slow and takes too much memory

### ISSUE THREAD

**Issue by vesper8** [spatie/laravel-db-snapshots#29]
I noticed one thing.. if I do a local create / load with a database .sql that is only 5mb in size. It goes very well

But when I do the same load for a 5mb database that's on S3.. on my production server it works but it's very slow, and on my dev is runs out of memory very quickly.. which leads me to think you're streaming the data from S3 ? rather than copying it locally first and then importing it locally?

Something's off.. because I only go out of memory when loading from S3

**Comment by vesper8** [comment]
want to add, I tried this `php -d memory_limit=256M artisan snapshot:load mySnapshot`

And then things exploded.. into the biggest wall of red I've ever witnessed :

```
[Doctrine\DBAL\Driver\PDOException]
  SQLSTATE[08S01]: Communication link failure: 1153 Got a packet bigger than 'max_allowed_packet' bytes
```

**Comment by freekmurze** [comment]
Going to leave this as is for now. Thanks for sharing your solution, will be helpful for other users that have the same problem.
