### ISSUE TITLE
Dead link in the description of the repository

### ISSUE THREAD

**Issue by miclf** [spatie/laravel-db-snapshots#40]
The link in the top description of the repository (see image below) [goes to a `404 Not Found`](https://murze.be/2017/03/laravel-package-quickly-dump-dump-database/).

It should be replaced by this new URL instead: https://murze.be/a-laravel-package-to-quickly-dump-and-load-the-database

![foo](https://user-images.githubusercontent.com/3188746/38167627-82be9838-3538-11e8-8ed4-a068596ae348.png)

**Comment by freekmurze** [comment]
Fixed
