### ISSUE TITLE
fclose(): supplied resource is not a valid stream resource 

### ISSUE THREAD

**Issue by Gummibeer** [spatie/laravel-db-snapshots#43]
> **In SnapshotFactory.php line 78:**
> fclose(): supplied resource is not a valid stream resource
https://github.com/spatie/laravel-db-snapshots/blob/master/src/SnapshotFactory.php#L78

The problem is caused by the Microsoft Azure Blob Storage package. After a lot of dumps and debugging I got to the point where the type of the passed resource changes from `stream` to `Unknown` after the `wait()` call. https://github.com/Azure/azure-storage-php/blob/d4488ca/azure-storage-blob/src/Blob/BlobRestProxy.php#L1661-L1672

But the real "problem" comes from the guzzle package Stream class that is used and closes the original stream on destruct. https://github.com/guzzle/psr7/blob/master/src/Stream.php#L110

Because I think that the guzzle package is a common solution for http requests und streams I would want to see a solution in this package a simple `is_resource($file)` should be enough to prevent this exception.

**Comment by freekmurze** [comment]
Fix has been tagged.
