### ISSUE TITLE
 "'pg_dump'" is not recognized

### ISSUE THREAD

**Issue by jjpotestad** [spatie/laravel-db-snapshots#45]
$ php artisan snapshot:create
Creating new snapshot...

In DumpFailed.php line 17:

  The dump process failed with exitcode 1 : General error : could not find a "'pg_dump'" is not recognized as an internal or external command, operable program or batch file.

//- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
// I have already configured the postgres environment variable
// When I write in Git CMD everything is fine
//- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

>pg_dump --version
pg_dump (PostgreSQL) 9.3.4

//- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
// But when I write in Git Bash the same command
//- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

$ pg_dump --version
bash: pg_dump: command not found

//- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
// I'm working with Laravel 5.5, Postgres 9.3.4 and Windows 10
//- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

Any idea?
Could it be because I do not use Linux?

**Comment by freekmurze** [comment]
It's probably a problem with permissions. Make sure your PHP process has the right permission to call binaries.

You could test this by extracting the dump command from our package to your own dummy script and running that separately.

**Comment by jjpotestad** [comment]
Now i changed to linux and works perfect. Thanks

**Comment by raymondtri** [comment]
The issue here is actually coming back up again. It appears that on line 66 of vendors/spatie/db-dumper/src/Databases/PostgreSql.php there is an extra apostrophe wrapping that really screws with windows. This package is only functional on linux systems due to that. The easy fix is simply removing the extra single apostrophes.
