### ISSUE TITLE
Error on max_allowed_package

### ISSUE THREAD

**Issue by computerlyrik** [spatie/laravel-db-snapshots#46]
Hi there,

how do i add the ```max_allowed_package=8M``` correctly to additional options when starting
```snapshot:create```?

failed on ```    'dump' => ['add_extra_option' => '--max_allowed_packet=8M'], ``` within ```config/db-snapshots.php```

**Comment by freekmurze** [comment]
Currently there is no way of passing options to the db dumper. I'd accept a fully tested and documented PR that adds this to the package.
