### ISSUE TITLE
Indicate folder foreach snapshots

### ISSUE THREAD

**Issue by Hydro8** [spatie/laravel-db-snapshots#51]
Hi

Is it possible to add one level of folder to snapshots ?

I save a lot of DB, so in my snapshot folder I have every snapshots. Instead I would have a folder foreach db.

For example, my db name is ZC001 so my snapshots will be save to /snapshots/ZC001/.... and if my db name is ZC002, snapshots will be save to /snapshots/ZC002/...

Is it possible right now ?

Thank for your work !

**Comment by freekmurze** [comment]
This isn't possible now. Because most users don't need this and I like to keep the package simple, I'm probably not going to add this feature.
