### ISSUE TITLE
mariadb

### ISSUE THREAD

**Issue by alexeydg** [spatie/laravel-db-snapshots#55]
Do I understand correctly that this plugin does not support mariadb?
laravel.ERROR: Cannot create a dumper for db driver `mariadb`. Use `mysql`, `pgsql` or `sqlite`. {"exception":"[object] (Spatie\\DbSnapshots\\Exceptions\\CannotCreateDbDumper(code: 0): Cannot create a dumper for db driver `mariadb`. Use `mysql`, `pgsql` or `sqlite`. at /vendor/spatie/laravel-db-snapshots/src/Exceptions/CannotCreateDbDumper.php:11)

**Comment by freekmurze** [comment]
It support mariadb, but your driver should be `mysql`.
