### ISSUE TITLE
Add option for compressing snapshots

### ISSUE THREAD

**Issue by jimbojsb** [spatie/laravel-db-snapshots#56]
It would be useful, I think, for larger snapshots that might exist on a cloud storage service filesystem, to support the option to gzip the resulting .sql file

**Comment by freekmurze** [comment]
If the code for this is simple and well tested, I’d accept a PR that adds the proposed feature to the package.

**Comment by jimbojsb** [comment]
@freekmurze i took a look at this, it's not trivial. There are quite a few places where filenames would have to be passed around and to do it cleanly would require refactoring a good bit of the codebase. I'm not sure it's worth the level of modifications required, it may make more sense to decorate this package with another one or some similar strategy that leaves this package untouched or largely untouched.
