### ISSUE TITLE
Dum process error

### ISSUE THREAD

**Issue by Hydro8** [spatie/laravel-db-snapshots#58]
Hi

I used spatie snapshots months ago with success, great tool.

Now we change our server, so I migrate my laravel installation but now spatie snapshots don't work anymore.

I tried with cmd : "php artisan snapshot:create test" and it said : 

> In DumpFailed.php line 17: 
> The dump process failed with exitcode 1 : General error : Le chemin d'accès spécifié est introuvable.

I tried to remove it (with bugs) and reinstalled it but nothing change.

I check my app config for the right temporary_directory_path folder and it's ok.

Any idea for this error ?

Laravel : 5.6.39
Spatie : last version
PHP : 7.2.11

Thank

**Comment by freekmurze** [comment]
This probably has something to do with the location of `mysqldump`. First hunch is that it is not installed on your system or maybe your php process does not have the right permission to call it.

**Comment by Hydro8** [comment]
I can access to mysqldump from command line or from cmder inside laragon :/

**Comment by Hydro8** [comment]
Do you think other things can cause this problem ?
I use laragon, do I need to install standalone php ?

**Comment by Hydro8** [comment]
Any update on my problem's?
