### ISSUE TITLE
Ignore certain db tables

### ISSUE THREAD

**Issue by jamesmills** [spatie/laravel-db-snapshots#60]
Hi,

We have a rather big database in production. I would like to sync the production db with local but I want to be able to exclude some of the tables which are huge. Have you thought about this use for this package or am I looking in the wrong place?

Thanks

**Comment by freekmurze** [comment]
The database dump in this dump are done via another package of ours: db-dumper.

laravel-db-tables [passes any parameter in the `dump` section](https://github.com/spatie/laravel-db-snapshots/blob/7b54b02fc10a3a60dae59d8b7ffa46a9692f6815/src/DbDumperFactory.php#L33-L35) of the database config to db-dumper.

Db-dumper has [a method `excludeTables`](https://github.com/spatie/db-dumper#excluding-tables-from-the-dump).

I haven't tested this, but I'm thinking you should just add a `dump` section to your db config with a key `excludeTables` and as the value the tables you don't want comma separated.

Good luck!
