### ISSUE TITLE
Loading PostgreSQL dumps does not work

### ISSUE THREAD

**Issue by skollro** [spatie/laravel-db-snapshots#61]
Hello,

I've just encountered the issue that snapshots of PostgreSQL databases can not be loaded, because the `COPY` command is used in the `dump.sql` file.

I would propose to alter `DbDumperFactory@forDriver` in a way that the `PostgreSql` instance is returned with `useInserts` by default. So it works without having a `dump => ['use_inserts']` option in `database.php`, which you maybe don't want if you're using laravel-backup as well, because `COPY` is more performant.

Proposed solution:
```
if ($driver === 'pgsql') {
    return (new PostgreSql())->useInserts();
}
```

**Comment by freekmurze** [comment]
Feel free to PR this with tests.

**Comment by rdpascua** [comment]
@skollro but how can I use copy instead of inserts now?

**Comment by skollro** [comment]
COPY didn‘t work before anyway, because the package doesn’t import the sql file using the CLI (which is required for COPY to work). However, I think this package has been created for development environments, so performance is not that important. As COPY and inserts are equivalent in terms of functionality, they‘re fully interchangeable.
