### ISSUE TITLE
Deprecated Implementation

### ISSUE THREAD

**Issue by bayareawebpro** [spatie/laravel-db-snapshots#66]
Just thought I would let you know I got this message.  Looks like we need to use the static method "fromShellCommandline" instead when using string commands.

```
Passing a command as string when creating a "Symfony\Component\Process\Process" instance is deprecated since Symfony 4.2, pass it as an array of its arguments instead, or use the "Process::fromShellCommandline()" constructor if you need features provided by the shell.

```

**Comment by riasvdv** [comment]
Running a `composer update` should fix this, as this package requires our https://github.com/spatie/db-dumper package where this issue was fixed in a newer release.
