### ISSUE TITLE
General error : "'pg_dump'" 

### ISSUE THREAD

**Issue by parrotsoft** [spatie/laravel-db-snapshots#69]
Hello, I have the following error:

`$ php artisan snapshot:create my-first-dumpd
Creating new snapshot...

In DumpFailed.php line 17:

  The dump process failed with exitcode 1 : General error : "'pg_dump'" no se reconoce como un comando interno o externo,
  programa o archivo por lotes ejecutable.
`

I'm using windows 10 and postgresql 9. 

What can be? Thank you.

**Comment by freekmurze** [comment]
This seems to be a permissions problem or maybe you don't have `pg_dump` installed. Either way, this problem is not caused by this package.
