### ISSUE TITLE
snapshot:load fails with DB >100Mb

### ISSUE THREAD

**Issue by MarcelHoogAntink** [spatie/laravel-db-snapshots#71]
php artisan snapshot:load fails with big databases (>100 Mb) 
the databases were stored with snapshot:create

**Comment by freekmurze** [comment]
Seems to me that this problem is caused by your environment and not our package.

Which error message are you getting?

**Comment by MarcelHoogAntink** [comment]
The message is:

  Symfony\Component\Debug\Exception\FatalErrorException  : Allowed memory size of 134217728 bytes exhausted (tried to allocate 138605824 bytes)

  at C:\Users\marcel.hoog.antink\Homestead\code\mijnknwuDevelop2\vendor\league\flysystem\src\Adapter\Local.php:223
    219|      */
    220|     public function read($path)
    221|     {
    222|         $location = $this->applyPathPrefix($path);
    223|         $contents = @file_get_contents($location);
    224|
    225|         if ($contents === false) {
    226|             return false;
    227|         }``

**Comment by freekmurze** [comment]
Try increasing the memory available to PHP.

**Comment by MarcelHoogAntink** [comment]
Thanks for your reply!
I increased the memory from 512M to 2048M
Little Db's still work fine.
Bigger ones give `Error while sending QUERY packet.` and echo's the whole file on screen.

**Comment by kw-pr** [comment]
This is still a problem with your environment.

Quick google for the error
=> https://stackoverflow.com/questions/30753674/error-while-sending-query-packet

Have a look at `max_allowed_packet`

**Comment by MarcelHoogAntink** [comment]
That did it !! 
Thanks!!

(I was not looking for a MySQL-setting because MySQL workbench worked with these large files, and it uses also mysqldump)

**Comment by bilfeldt** [comment]
Hi. I am just trying to understand the details of the code here, but does [src/Snapshot.php@L53](https://github.com/spatie/laravel-db-snapshots/blob/621ab848a885bf2809010d1ec5cb3a00f1a52352/src/Snapshot.php#L53): 
```php
$dbDumpContents = $this->disk->get($this->fileName);//$this->fileName is a string
```
not read the entire content of the dump into a variable that could potentially be a lot bigger than the memory limit of the system? The content is then passed to the database in [src/Snapshot.php@L59](https://github.com/spatie/laravel-db-snapshots/blob/621ab848a885bf2809010d1ec5cb3a00f1a52352/src/Snapshot.php#L59):

```php
DB::connection($connectionName)->unprepared($dbDumpContents);
```

Would it be possible to use streams to read the content of large dumps and stream those to the database to avoid any memory limit issues?

**Comment by freekmurze** [comment]
Feel free to send a PR for this.

**Comment by bilfeldt** [comment]
I think a way to do this could be as follows:

## Splitting SQL into chunks
The SQL file can be split into chunks (each chunk must be below the memory limit) and each chunk executed one at a time.

There is an article on how to do this using a PDO here: [Import MySQL large database SQL file using PDO](https://bedigit.com/blog/import-mysql-large-database-sql-file-using-pdo/). Note that it's not as trivial as executing line by line but instead each SQL statement must be read (can be multiple lines) and executed one at a time. The article does so by searching for semicolor which should mark the end of a line in SQL.

Maybe some inspiration can also be found from the fantastic Laravel Excel package which can also [read CSV files in chunks](https://docs.laravel-excel.com/3.1/imports/chunk-reading.html), but one should note that this is done simply line by line.

## Reading large SQL file
The best way to read large SQL files would probably to stream the content as explained in the [Flysystem documentation](https://flysystem.thephpleague.com/docs/usage/filesystem-api/#read-files-as-a-stream) - an example can be found [here](https://flysystem.thephpleague.com/docs/usage/filesystem-api/#using-streams-for-reads-and-writes).

So we would need to stream the SQL file content to a variable `$sqlDumptStatement` until a complete SQL statement is read, at which point we then need to execte the statement using the existing code:
```php
DB::connection($connectionName)->unprepared($sqlDumptStatement);
```
Once done then we clear the variable `$sqlDumptStatement` and continue reading the next SQL statement and so on.

**Comment by pelmered** [comment]
I made an implementation of this in a PR here: https://github.com/spatie/laravel-db-snapshots/pull/93
