### ISSUE TITLE
snapshot:load does not use connection as configured in config file.

### ISSUE THREAD

**Issue by boogiebug** [spatie/laravel-db-snapshots#90]
The `snapshot:create` command run correctly using configurations from db-snapshot.php config file. But `snapshot:load` command use only the `--connection`.

The following code is my proposed fix:

**File**: src/Commands/Load.php Line 43

Original:
```PHP
        $snapshot->load($this->option('connection'));
```

Fix:
```PHP
        $connectionName = $this->option('connection')
            ?: config('db-snapshots.default_connection')
            ?? config('database.default');
        $snapshot->load($connectionName);
```

**Comment by freekmurze** [comment]
Feel free to PR this! 👍
