### ISSUE TITLE
Loading (importing) large DB dumps (2.1GB) fails - Out of memory

### ISSUE THREAD

**Issue by CristianSitov** [spatie/laravel-db-snapshots#92]
I have a system were DB has to be copied daily from Production to Stage.
Exporting DB with `snapshot:create` works smooth & fast given the large DB. However, importing it on Stage (a 2GB-sized snapshot) it fails in different places on EC2 t2.large machine.

```
[ec2-user@ip-1... current]$ php -d memory_limit=-1 artisan snapshot:load prod_2020-05-08 -vvv

mmap() failed: [12] Cannot allocate memory
PHP Fatal error:  Out of memory (allocated 6535892992) (tried to allocate 1877143816 bytes) in /var/app/current/vendor/laravel/framework/src/Illuminate/Support/Str.php on line 419

In Str.php line 419:

  Out of memory (allocated 6535892992) (tried to allocate 1877143816 bytes)

```

**Comment by pelmered** [comment]
I just made a PR for this here: https://github.com/spatie/laravel-db-snapshots/pull/93

Se if it solves the problem for you. The load command now streams the file into the database without loading the whole file info a variable.

**Comment by ralphschindler** [comment]
@pelmered thanks for the effort, this is the reason we stopped using this package, but would love to come back to it. Instead of sending queries (generated by the external `mysqldump`) through the database connection, why not just stream them through the external/command-line `mysql` command? is that an option you considered?

(see the loadSnapshot() method: https://ralphschindler.dev/article/how-we-database-in-laravel/ - clearly we have baked in hard coded paths that work in our docker containers that wouldn't work if it were not dockerized, but you get the picture).

**Comment by pelmered** [comment]
@ralphschindler Okay, interesting. 
I have built a similar system to what you are describing where I can pull down a snapshot from production down to the local dev environment with a simple artisan command. The command also sets some other things in the database to make it safe for development. 
We also have a snapshot rotate script. We actually take snapshot every 5 minutes and then rotate the snapshots. We save all snapshots for the last 24 hours, 12 for day 2-3, 6 for day 4-10,  2 for the last month and then 1 per day for the last year. That makes sure that we always have a recent backup and that you can pull down the production database that is no more than 5 minutes old.

Yes, using an external command would be a good idea as well. But that would require more dependencies for this to run and requires more from the environment. Would that work at all on Windows for example?

**Comment by trevorgehman** [comment]
> I have built a similar system to what you are describing where I can pull down a snapshot from production down to the local dev environment with a simple artisan command. The command also sets some other things in the database to make it safe for development.

Can you possibly share what you did? I really like what @ralphschindler did but I'm trying to figure out a way to sanitize production data as a part of the workflow.
