### ISSUE TITLE
--latest argument does not returns latest

### ISSUE THREAD

**Issue by stefanius** [spatie/laravel-db-snapshots#99]
Since a while I discovered that snapshots are not loaded correctly. We already uses an extension of the ```Load.php``` class to find the latest snapshot. But that doesnt work anymore because in the original package is also added a --latest option and it does not returns the latest.

In short:

- The list of snapshots ($snapShots) is sorted descending (the newest snapshot is on top, the oldest on the bottom)
- On this moment the last snapshot is picked (the last item on the list, is the first snapshot that is created)
- I can't see a use case for this behaviour but if there is any, maybe the attribute should be renamed to 'oldest'.
- I added a pull request to fix this bug 

![image](https://user-images.githubusercontent.com/2707905/86465284-a0614d80-bd31-11ea-89fc-0c01f7e968b2.png)

**Comment by stefanius** [comment]
PR: https://github.com/spatie/laravel-db-snapshots/pull/100

**Comment by freekmurze** [comment]
We'll continue this in #100
